export const GAME_FIELD_WIDTH = 20;
export const INITAL_SNAKE_LENGTH = 3;
export const SNAKE_SPEED = 200;

export const DIRECTION_RIGHT = 'DIRECTION_RIGHT';
export const DIRECTION_LEFT = 'DIRECTION_LEFT';
export const DIRECTION_UP = 'DIRECTION_UP';
export const DIRECTION_DOWN = 'DIRECTION_DOWN';
